"""Add url column to videos

Revision ID: 4cc7c496d25b
Revises: 71bcb082aed8
Create Date: 2025-05-21 16:18:37.972156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc7c496d25b'
down_revision: Union[str, None] = '71bcb082aed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('videos', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###
